### ISSUE TITLE
Genial las rutas

### ISSUE THREAD

**Issue by vicenlu** [FabrizioContu/SPRINT_7#1]
Quizás hubiese procedido de la siguiente manera:
- Crear una ruta para el detalle de las naves. Con routing dinámico, pasando el id de la nave en cuestión en la ruta. 
- Después usaría useParams() en el detalle de la nave para obtener el id de dicha nave.
- Con el id de la nave, pediría al context los datos de la nave.

https://github.com/FabrizioContu/SPRINT_7/blob/37c361f69a61e73f5958e870b6e136321902eaaa/src/App.tsx#L26

**Comment by FabrizioContu** [comment]
Hecho. 
He creado un nuevo componente que renderiza los detalles de cada nave con un routing dinamico.
